### ISSUE TITLE
Help is not easy to discover

### ISSUE THREAD

**Issue by clach04** [pldubouilh/gossa-ui#18]
Readme in https://github.com/pldubouilh/gossa#shortcuts does make clear what the help key combo is, but it is not discoverable in UI.

**Comment by clach04** [comment]
@pldubouilh What are your thoughts on adding a question mark icon, "?" or the text "CTRL-h for help" in the top right hand corner in the https://github.com/pldubouilh/gossa-ui/blob/master/ui.tmpl#L48 "icHolder" DIV?

**Comment by clach04** [comment]
BTW thanks for making https://github.com/pldubouilh/gossa available, I've been playing with it this evening. Super easy to deploy/use! Nice job 👍

**Comment by pldubouilh** [comment]
thanks :) 

I agree, it's a pretty significant part of the UX and it's currently mostly hidden to users.

maybe a `?` on the bottom right corner ? Or maybe showing the help on browsers that never visited the gossa instance before ?
